[tox]
envlist = py3

[testenv]
deps=-r{toxinidir}/requirements.txt
     -r{toxinidir}/test-requirements.txt

commands=
   pytest --cov=ideastatica_connection_api

[pytest]
markers =
    requires_service: drives a Connection REST API service running at http://localhost:5000; not run by CI
