# flake8: noqa

# import apis into api package
from ideastatica_connection_api.api.calculation_api import CalculationApi
from ideastatica_connection_api.api.client_api import ClientApi
from ideastatica_connection_api.api.connection_api import ConnectionApi
from ideastatica_connection_api.api.conversion_api import ConversionApi
from ideastatica_connection_api.api.export_api import ExportApi
from ideastatica_connection_api.api.load_effect_api import LoadEffectApi
from ideastatica_connection_api.api.material_api import MaterialApi
from ideastatica_connection_api.api.member_api import MemberApi
from ideastatica_connection_api.api.operation_api import OperationApi
from ideastatica_connection_api.api.parameter_api import ParameterApi
from ideastatica_connection_api.api.presentation_api import PresentationApi
from ideastatica_connection_api.api.project_api import ProjectApi
from ideastatica_connection_api.api.report_api import ReportApi
from ideastatica_connection_api.api.template_api import TemplateApi

