/*
 * Connection Rest API 4.0
 *
 * IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: info@ideastatica.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using IdeaRS.OpenModel;
using IdeaRS.OpenModel.Connection;
using IdeaRS.OpenModel.Result;
using IdeaStatiCa.Api.Connection.Model;
using IdeaStatiCa.Api.Connection.Model.Connection;
using IdeaStatiCa.Api.Connection.Model.Material;
using IdeaStatiCa.Api.Connection.Model.Conversion;
using IdeaStatiCa.ConnectionApi.Client;
using IdeaStatiCa.ConnectionApi.Model;

namespace IdeaStatiCa.ConnectionApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICalculationJobsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        ConCalculationJob CancelCalculationJob(Guid projectId, Guid jobId, int operationIndex = 0);

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        ApiResponse<ConCalculationJob> CancelCalculationJobWithHttpInfo(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        ConCalculationJob GetCalculationJob(Guid projectId, Guid jobId, int operationIndex = 0);

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        ApiResponse<ConCalculationJob> GetCalculationJobWithHttpInfo(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        ConCalculationJob StartCalculation(Guid projectId, List<int> requestBody, int operationIndex = 0);

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        ApiResponse<ConCalculationJob> StartCalculationWithHttpInfo(Guid projectId, List<int> requestBody, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        ConCalculationJob StartConnectionCalculation(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), int operationIndex = 0);

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="connectionId">The ID of the connection to calculate.</param>
/// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        ApiResponse<ConCalculationJob> StartConnectionCalculationWithHttpInfo(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), string requestedType = null, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICalculationJobsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        System.Threading.Tasks.Task<ConCalculationJob> CancelCalculationJobAsync(Guid projectId, Guid jobId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConCalculationJob>> CancelCalculationJobWithHttpInfoAsync(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        System.Threading.Tasks.Task<ConCalculationJob> GetCalculationJobAsync(Guid projectId, Guid jobId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConCalculationJob>> GetCalculationJobWithHttpInfoAsync(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        System.Threading.Tasks.Task<ConCalculationJob> StartCalculationAsync(Guid projectId, List<int> requestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConCalculationJob>> StartCalculationWithHttpInfoAsync(Guid projectId, List<int> requestBody, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        System.Threading.Tasks.Task<ConCalculationJob> StartConnectionCalculationAsync(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection.
        /// </summary>
        /// <remarks>
        /// Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </remarks>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConCalculationJob>> StartConnectionCalculationWithHttpInfoAsync(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICalculationJobsApi : ICalculationJobsApiSync, ICalculationJobsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CalculationJobsApi : ICalculationJobsApi
    {
        private IdeaStatiCa.ConnectionApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CalculationJobsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CalculationJobsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CalculationJobsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CalculationJobsApi(string basePath)
        {
            this.Configuration = IdeaStatiCa.ConnectionApi.Client.Configuration.MergeConfigurations(
                IdeaStatiCa.ConnectionApi.Client.GlobalConfiguration.Instance,
                new IdeaStatiCa.ConnectionApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new IdeaStatiCa.ConnectionApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new IdeaStatiCa.ConnectionApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = IdeaStatiCa.ConnectionApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CalculationJobsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CalculationJobsApi(IdeaStatiCa.ConnectionApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = IdeaStatiCa.ConnectionApi.Client.Configuration.MergeConfigurations(
                IdeaStatiCa.ConnectionApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new IdeaStatiCa.ConnectionApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new IdeaStatiCa.ConnectionApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = IdeaStatiCa.ConnectionApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CalculationJobsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CalculationJobsApi(IdeaStatiCa.ConnectionApi.Client.ISynchronousClient client, IdeaStatiCa.ConnectionApi.Client.IAsynchronousClient asyncClient, IdeaStatiCa.ConnectionApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = IdeaStatiCa.ConnectionApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IdeaStatiCa.ConnectionApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public IdeaStatiCa.ConnectionApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IdeaStatiCa.ConnectionApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IdeaStatiCa.ConnectionApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        public ConCalculationJob CancelCalculationJob(Guid projectId, Guid jobId, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = CancelCalculationJobWithHttpInfo(projectId, jobId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        public IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> CancelCalculationJobWithHttpInfo(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            localVarRequestOptions.Operation = "CalculationJobsApi.CancelCalculationJob";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<ConCalculationJob>("/api/4/projects/{projectId}/calculation-jobs/{jobId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelCalculationJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        public async System.Threading.Tasks.Task<ConCalculationJob> CancelCalculationJobAsync(Guid projectId, Guid jobId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = await CancelCalculationJobWithHttpInfoAsync(projectId, jobId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Requests cancellation of an asynchronous calculation job: the in-flight solver process is  killed and remaining connections are skipped. Connections whose solve was interrupted stay  not-calculated; already completed connections keep their results. Idempotent — cancelling  a finished job leaves it unchanged. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob>> CancelCalculationJobWithHttpInfoAsync(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            localVarRequestOptions.Operation = "CalculationJobsApi.CancelCalculationJob";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<ConCalculationJob>("/api/4/projects/{projectId}/calculation-jobs/{jobId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelCalculationJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        public ConCalculationJob GetCalculationJob(Guid projectId, Guid jobId, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = GetCalculationJobWithHttpInfo(projectId, jobId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        public IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> GetCalculationJobWithHttpInfo(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            localVarRequestOptions.Operation = "CalculationJobsApi.GetCalculationJob";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<ConCalculationJob>("/api/4/projects/{projectId}/calculation-jobs/{jobId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCalculationJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        public async System.Threading.Tasks.Task<ConCalculationJob> GetCalculationJobAsync(Guid projectId, Guid jobId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = await GetCalculationJobWithHttpInfoAsync(projectId, jobId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the current state of an asynchronous calculation job: its status, the connection  currently being calculated with its per-load-case solver progress, and — once finished —  the result summaries. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="jobId">The id of the job returned by the calculate-async endpoints.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob>> GetCalculationJobWithHttpInfoAsync(Guid projectId, Guid jobId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            localVarRequestOptions.Operation = "CalculationJobsApi.GetCalculationJob";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ConCalculationJob>("/api/4/projects/{projectId}/calculation-jobs/{jobId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCalculationJob", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        public ConCalculationJob StartCalculation(Guid projectId, List<int> requestBody, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = StartCalculationWithHttpInfo(projectId, requestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        public IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> StartCalculationWithHttpInfo(Guid projectId, List<int> requestBody, string requestedType = null, int operationIndex = 0)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
            {
                throw new IdeaStatiCa.ConnectionApi.Client.ApiException(400, "Missing required parameter 'requestBody' when calling CalculationJobsApi->StartCalculation");
            }

            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "CalculationJobsApi.StartCalculation";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ConCalculationJob>("/api/4/projects/{projectId}/connections/calculate-async", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StartCalculation", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        public async System.Threading.Tasks.Task<ConCalculationJob> StartCalculationAsync(Guid projectId, List<int> requestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = await StartCalculationWithHttpInfoAsync(projectId, requestBody, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for the given connections. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise). Connection ids are validated upfront — an unknown id rejects the start with  404 before any job is registered. Like the synchronous bulk calculate, a connection that  fails to calculate produces a failed summary row in the job&#39;s results rather than  failing the job.
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="requestBody">List of connection IDs to calculate.</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob>> StartCalculationWithHttpInfoAsync(Guid projectId, List<int> requestBody, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
            {
                throw new IdeaStatiCa.ConnectionApi.Client.ApiException(400, "Missing required parameter 'requestBody' when calling CalculationJobsApi->StartCalculation");
            }


            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "CalculationJobsApi.StartCalculation";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ConCalculationJob>("/api/4/projects/{projectId}/connections/calculate-async", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StartCalculation", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConCalculationJob</returns>
        public ConCalculationJob StartConnectionCalculation(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = StartConnectionCalculationWithHttpInfo(projectId, connectionId, loadEffectIds);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
/// <param name="connectionId">The ID of the connection to calculate.</param>
/// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConCalculationJob</returns>
        public IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> StartConnectionCalculationWithHttpInfo(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (loadEffectIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToMultiMap("multi", "loadEffectIds", loadEffectIds));
            }

            localVarRequestOptions.Operation = "CalculationJobsApi.StartConnectionCalculation";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ConCalculationJob>("/api/4/projects/{projectId}/connections/{connectionId}/calculate-async", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StartConnectionCalculation", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConCalculationJob</returns>
        public async System.Threading.Tasks.Task<ConCalculationJob> StartConnectionCalculationAsync(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob> localVarResponse = await StartConnectionCalculationWithHttpInfoAsync(projectId, connectionId, loadEffectIds, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Starts an asynchronous CBFEM calculation job for a single connection. Returns 202 with the accepted job immediately; poll it with the calculation-jobs GET  endpoint and cancel it with DELETE. At most one job can be active per project (409  otherwise).
        /// </summary>
        /// <exception cref="IdeaStatiCa.ConnectionApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">The unique identifier of the opened project in the ConnectionRestApi service.</param>
        /// <param name="connectionId">The ID of the connection to calculate.</param>
        /// <param name="loadEffectIds">Optional subset of load-effect ids of this connection to solve. When set,              exactly these load effects are analysed - their Active flags are ignored and nothing is persisted;              results - including subsequent results, raw-results, result-mesh and report reads - reflect only              this subset until the next calculation. When omitted, all active load effects are solved; an empty              list is treated as omitted. Unknown ids are rejected with 422. (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConCalculationJob)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.ConnectionApi.Client.ApiResponse<ConCalculationJob>> StartConnectionCalculationWithHttpInfoAsync(Guid projectId, int connectionId, List<int> loadEffectIds = default(List<int>), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.ConnectionApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.ConnectionApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.ConnectionApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (loadEffectIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(IdeaStatiCa.ConnectionApi.Client.ClientUtils.ParameterToMultiMap("multi", "loadEffectIds", loadEffectIds));
            }

            localVarRequestOptions.Operation = "CalculationJobsApi.StartConnectionCalculation";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ConCalculationJob>("/api/4/projects/{projectId}/connections/{connectionId}/calculate-async", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StartConnectionCalculation", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
