/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// Check summary
    /// </summary>
    [DataContract(Name = "CheckResSummary")]
    public partial class CheckResSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckResSummary" /> class.
        /// </summary>
        /// <param name="checkValue">Check value.</param>
        /// <param name="checkStatus">Status of check.</param>
        /// <param name="loadCaseId">Id of Load Case.</param>
        /// <param name="name">Name.</param>
        /// <param name="unityCheckMessage">Detail message about overall check.</param>
        /// <param name="skipped">Whether the check was calculated or not.  If true, the check was not calculated and IdeaRS.OpenModel.Connection.CheckResSummary.CheckValue should be ignored, otherwise false..</param>
        public CheckResSummary(double checkValue = default(double), bool checkStatus = default(bool), int loadCaseId = default(int), string name = default(string), string unityCheckMessage = default(string), bool skipped = default(bool))
        {
            this.CheckValue = checkValue;
            this.CheckStatus = checkStatus;
            this.LoadCaseId = loadCaseId;
            this.Name = name;
            this.UnityCheckMessage = unityCheckMessage;
            this.Skipped = skipped;
        }

        /// <summary>
        /// Check value
        /// </summary>
        /// <value>Check value</value>
        [DataMember(Name = "checkValue", EmitDefaultValue = false)]
        public double CheckValue { get; set; }

        /// <summary>
        /// Status of check
        /// </summary>
        /// <value>Status of check</value>
        [DataMember(Name = "checkStatus", EmitDefaultValue = true)]
        public bool CheckStatus { get; set; }

        /// <summary>
        /// Id of Load Case
        /// </summary>
        /// <value>Id of Load Case</value>
        [DataMember(Name = "loadCaseId", EmitDefaultValue = false)]
        public int LoadCaseId { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        /// <value>Name</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Detail message about overall check
        /// </summary>
        /// <value>Detail message about overall check</value>
        [DataMember(Name = "unityCheckMessage", EmitDefaultValue = true)]
        public string UnityCheckMessage { get; set; }

        /// <summary>
        /// Whether the check was calculated or not.  If true, the check was not calculated and IdeaRS.OpenModel.Connection.CheckResSummary.CheckValue should be ignored, otherwise false.
        /// </summary>
        /// <value>Whether the check was calculated or not.  If true, the check was not calculated and IdeaRS.OpenModel.Connection.CheckResSummary.CheckValue should be ignored, otherwise false.</value>
        [DataMember(Name = "skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckResSummary {\n");
            sb.Append("  CheckValue: ").Append(CheckValue).Append("\n");
            sb.Append("  CheckStatus: ").Append(CheckStatus).Append("\n");
            sb.Append("  LoadCaseId: ").Append(LoadCaseId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UnityCheckMessage: ").Append(UnityCheckMessage).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
