/*
 * Connection Rest API 1.0
 *
 * IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// ConAlignedPlate
    /// </summary>
    [DataContract(Name = "ConAlignedPlate")]
    public partial class ConAlignedPlate
    {

        /// <summary>
        /// Gets or Sets PlateSide
        /// </summary>
        [DataMember(Name = "plateSide", EmitDefaultValue = false)]
        public ConAlignedPlateSideCodeEnum? PlateSide { get; set; }

        /// <summary>
        /// Gets or Sets PartType
        /// </summary>
        [DataMember(Name = "partType", EmitDefaultValue = false)]
        public ConMemberPlatePartTypeEnum? PartType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConAlignedPlate" /> class.
        /// </summary>
        /// <param name="plateSide">plateSide.</param>
        /// <param name="memberId">memberId.</param>
        /// <param name="partType">partType.</param>
        public ConAlignedPlate(ConAlignedPlateSideCodeEnum? plateSide = default(ConAlignedPlateSideCodeEnum?), int memberId = default(int), ConMemberPlatePartTypeEnum? partType = default(ConMemberPlatePartTypeEnum?))
        {
            this.PlateSide = plateSide;
            this.MemberId = memberId;
            this.PartType = partType;
        }

        /// <summary>
        /// Gets or Sets MemberId
        /// </summary>
        [DataMember(Name = "memberId", EmitDefaultValue = false)]
        public int MemberId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConAlignedPlate {\n");
            sb.Append("  PlateSide: ").Append(PlateSide).Append("\n");
            sb.Append("  MemberId: ").Append(MemberId).Append("\n");
            sb.Append("  PartType: ").Append(PartType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
