/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// ConLoadSettings
    /// </summary>
    [DataContract(Name = "ConLoadSettings")]
    public partial class ConLoadSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConLoadSettings" /> class.
        /// </summary>
        /// <param name="loadsInEquilibrium">loadsInEquilibrium.</param>
        /// <param name="loadsInPercentage">loadsInPercentage.</param>
        public ConLoadSettings(bool loadsInEquilibrium = default(bool), bool loadsInPercentage = default(bool))
        {
            this.LoadsInEquilibrium = loadsInEquilibrium;
            this.LoadsInPercentage = loadsInPercentage;
        }

        /// <summary>
        /// Gets or Sets LoadsInEquilibrium
        /// </summary>
        [DataMember(Name = "loadsInEquilibrium", EmitDefaultValue = true)]
        public bool LoadsInEquilibrium { get; set; }

        /// <summary>
        /// Gets or Sets LoadsInPercentage
        /// </summary>
        [DataMember(Name = "loadsInPercentage", EmitDefaultValue = true)]
        public bool LoadsInPercentage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConLoadSettings {\n");
            sb.Append("  LoadsInEquilibrium: ").Append(LoadsInEquilibrium).Append("\n");
            sb.Append("  LoadsInPercentage: ").Append(LoadsInPercentage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
