/*
 * Connection Rest API 1.0
 *
 * IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// Defines ConMemberPlatePartTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConMemberPlatePartTypeEnum
    {
        /// <summary>
        /// Enum NotSpecified for value: notSpecified
        /// </summary>
        [EnumMember(Value = "notSpecified")]
        NotSpecified = 1,

        /// <summary>
        /// Enum TopFlange for value: topFlange
        /// </summary>
        [EnumMember(Value = "topFlange")]
        TopFlange = 2,

        /// <summary>
        /// Enum BottomFlange for value: bottomFlange
        /// </summary>
        [EnumMember(Value = "bottomFlange")]
        BottomFlange = 3,

        /// <summary>
        /// Enum BothFlanges for value: bothFlanges
        /// </summary>
        [EnumMember(Value = "bothFlanges")]
        BothFlanges = 4,

        /// <summary>
        /// Enum Web for value: web
        /// </summary>
        [EnumMember(Value = "web")]
        Web = 5,

        /// <summary>
        /// Enum AllCssParts for value: allCssParts
        /// </summary>
        [EnumMember(Value = "allCssParts")]
        AllCssParts = 6,

        /// <summary>
        /// Enum BasePlate for value: basePlate
        /// </summary>
        [EnumMember(Value = "basePlate")]
        BasePlate = 7,

        /// <summary>
        /// Enum EndPlate for value: endPlate
        /// </summary>
        [EnumMember(Value = "endPlate")]
        EndPlate = 8,

        /// <summary>
        /// Enum PlateWidener for value: plateWidener
        /// </summary>
        [EnumMember(Value = "plateWidener")]
        PlateWidener = 9,

        /// <summary>
        /// Enum Stiffener for value: stiffener
        /// </summary>
        [EnumMember(Value = "stiffener")]
        Stiffener = 10,

        /// <summary>
        /// Enum Rib for value: rib
        /// </summary>
        [EnumMember(Value = "rib")]
        Rib = 11,

        /// <summary>
        /// Enum GussetPlate for value: gussetPlate
        /// </summary>
        [EnumMember(Value = "gussetPlate")]
        GussetPlate = 12,

        /// <summary>
        /// Enum FinPlate for value: finPlate
        /// </summary>
        [EnumMember(Value = "finPlate")]
        FinPlate = 13,

        /// <summary>
        /// Enum Flange for value: flange
        /// </summary>
        [EnumMember(Value = "flange")]
        Flange = 14,

        /// <summary>
        /// Enum CssArcSegment for value: cssArcSegment
        /// </summary>
        [EnumMember(Value = "cssArcSegment")]
        CssArcSegment = 15,

        /// <summary>
        /// Enum IsStub for value: isStub
        /// </summary>
        [EnumMember(Value = "isStub")]
        IsStub = 16,

        /// <summary>
        /// Enum Splice for value: splice
        /// </summary>
        [EnumMember(Value = "splice")]
        Splice = 17,

        /// <summary>
        /// Enum TonguePlate for value: tonguePlate
        /// </summary>
        [EnumMember(Value = "tonguePlate")]
        TonguePlate = 18,

        /// <summary>
        /// Enum LidPlate for value: lidPlate
        /// </summary>
        [EnumMember(Value = "lidPlate")]
        LidPlate = 19,

        /// <summary>
        /// Enum GeneralPlate for value: generalPlate
        /// </summary>
        [EnumMember(Value = "generalPlate")]
        GeneralPlate = 20,

        /// <summary>
        /// Enum Doubler for value: doubler
        /// </summary>
        [EnumMember(Value = "doubler")]
        Doubler = 21,

        /// <summary>
        /// Enum EndPlateOnFlanges for value: endPlateOnFlanges
        /// </summary>
        [EnumMember(Value = "endPlateOnFlanges")]
        EndPlateOnFlanges = 22,

        /// <summary>
        /// Enum BackingPlate for value: backingPlate
        /// </summary>
        [EnumMember(Value = "backingPlate")]
        BackingPlate = 23,

        /// <summary>
        /// Enum InsertedPlate for value: insertedPlate
        /// </summary>
        [EnumMember(Value = "insertedPlate")]
        InsertedPlate = 24,

        /// <summary>
        /// Enum IsNegative for value: isNegative
        /// </summary>
        [EnumMember(Value = "isNegative")]
        IsNegative = 25
    }

}
