/*
 * Connection Rest API 1.0
 *
 * IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// CRT IS check
    /// </summary>
    /// <value>CRT IS check</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CrtCompCheckIS
    {
        /// <summary>
        /// Enum IS800Cl74 for value: iS800_Cl_7_4
        /// </summary>
        [EnumMember(Value = "iS800_Cl_7_4")]
        IS800Cl74 = 1,

        /// <summary>
        /// Enum IS456Cl344 for value: iS456_Cl_34_4
        /// </summary>
        [EnumMember(Value = "iS456_Cl_34_4")]
        IS456Cl344 = 2
    }

}
