/*
 * Connection Rest API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IdeaStatiCa.ConnectionApi.Client.OpenAPIDateConverter;

namespace IdeaStatiCa.ConnectionApi.Model
{
    /// <summary>
    /// Cut method
    /// </summary>
    /// <value>Cut method</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CutMethod
    {
        /// <summary>
        /// Enum BoundingBox for value: boundingBox
        /// </summary>
        [EnumMember(Value = "boundingBox")]
        BoundingBox = 1,

        /// <summary>
        /// Enum Surface for value: surface
        /// </summary>
        [EnumMember(Value = "surface")]
        Surface = 2,

        /// <summary>
        /// Enum Mitre for value: mitre
        /// </summary>
        [EnumMember(Value = "mitre")]
        Mitre = 3,

        /// <summary>
        /// Enum SurfaceAll for value: surfaceAll
        /// </summary>
        [EnumMember(Value = "surfaceAll")]
        SurfaceAll = 4
    }

}
