# coding: utf-8

"""
    Connection Rest API 5.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 5.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from ideastatica_connection_api.models.con_slotted_hole import ConSlottedHole
from typing import Optional, Set
from typing_extensions import Self

class ConFastenerPosition(BaseModel):
    """
    ConFastenerPosition
    """ # noqa: E501
    x: Optional[Union[StrictFloat, StrictInt]] = None
    y: Optional[Union[StrictFloat, StrictInt]] = None
    grid_index: Optional[StrictInt] = Field(default=None, alias="gridIndex")
    slotted_holes: Optional[List[ConSlottedHole]] = Field(default=None, alias="slottedHoles")
    hook_rotation: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="hookRotation")
    __properties: ClassVar[List[str]] = ["x", "y", "gridIndex", "slottedHoles", "hookRotation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConFastenerPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in slotted_holes (list)
        _items = []
        if self.slotted_holes:
            for _item_slotted_holes in self.slotted_holes:
                if _item_slotted_holes:
                    _items.append(_item_slotted_holes.to_dict())
            _dict['slottedHoles'] = _items
        # set to None if slotted_holes (nullable) is None
        # and model_fields_set contains the field
        if self.slotted_holes is None and "slotted_holes" in self.model_fields_set:
            _dict['slottedHoles'] = None

        # set to None if hook_rotation (nullable) is None
        # and model_fields_set contains the field
        if self.hook_rotation is None and "hook_rotation" in self.model_fields_set:
            _dict['hookRotation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConFastenerPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "x": obj.get("x"),
            "y": obj.get("y"),
            "gridIndex": obj.get("gridIndex"),
            "slottedHoles": [ConSlottedHole.from_dict(_item) for _item in obj["slottedHoles"]] if obj.get("slottedHoles") is not None else None,
            "hookRotation": obj.get("hookRotation")
        })
        return _obj


