# coding: utf-8

"""
    Connection Rest API 5.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 5.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from ideastatica_connection_api.models.con_base_plate_contact_type import ConBasePlateContactType
from ideastatica_connection_api.models.con_shear_force_transfer_method import ConShearForceTransferMethod
from typing import Optional, Set
from typing_extensions import Self

class ConFoundationBlockDto(BaseModel):
    """
    ConFoundationBlockDto
    """ # noqa: E501
    concrete_material_id: Optional[StrictInt] = Field(default=None, alias="concreteMaterialId")
    offset_top: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetTop")
    offset_bottom: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetBottom")
    offset_left: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetLeft")
    offset_right: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetRight")
    height: Optional[Union[StrictFloat, StrictInt]] = None
    shear_force_transfer: Optional[ConShearForceTransferMethod] = Field(default=None, alias="shearForceTransfer")
    contact_type: Optional[ConBasePlateContactType] = Field(default=None, alias="contactType")
    mortar_thickness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="mortarThickness")
    __properties: ClassVar[List[str]] = ["concreteMaterialId", "offsetTop", "offsetBottom", "offsetLeft", "offsetRight", "height", "shearForceTransfer", "contactType", "mortarThickness"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConFoundationBlockDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConFoundationBlockDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "concreteMaterialId": obj.get("concreteMaterialId"),
            "offsetTop": obj.get("offsetTop"),
            "offsetBottom": obj.get("offsetBottom"),
            "offsetLeft": obj.get("offsetLeft"),
            "offsetRight": obj.get("offsetRight"),
            "height": obj.get("height"),
            "shearForceTransfer": obj.get("shearForceTransfer"),
            "contactType": obj.get("contactType"),
            "mortarThickness": obj.get("mortarThickness")
        })
        return _obj


