# coding: utf-8

"""
    Connection Rest API 4.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 4.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from ideastatica_connection_api.models.con_css_choice_dimension import ConCssChoiceDimension
from ideastatica_connection_api.models.con_css_count_dimension import ConCssCountDimension
from ideastatica_connection_api.models.con_css_number_dimension import ConCssNumberDimension
from ideastatica_connection_api.models.con_css_switch_dimension import ConCssSwitchDimension
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CONCROSSSECTIONPARAMETRICDEFINITIONALLOFDIMENSIONS_ONE_OF_SCHEMAS = ["ConCssChoiceDimension", "ConCssCountDimension", "ConCssNumberDimension", "ConCssSwitchDimension"]

class ConCrossSectionParametricDefinitionAllOfDimensions(BaseModel):
    """
    Polymorphic root. Every element on the wire is one of the concrete subtypes listed in the discriminator mapping and carries the $type discriminator; $type is deliberately declared on each subtype schema (with its exact wire value as default) rather than here.
    """
    # data type: ConCssNumberDimension
    oneof_schema_1_validator: Optional[ConCssNumberDimension] = None
    # data type: ConCssCountDimension
    oneof_schema_2_validator: Optional[ConCssCountDimension] = None
    # data type: ConCssSwitchDimension
    oneof_schema_3_validator: Optional[ConCssSwitchDimension] = None
    # data type: ConCssChoiceDimension
    oneof_schema_4_validator: Optional[ConCssChoiceDimension] = None
    actual_instance: Optional[Union[ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension]] = None
    one_of_schemas: Set[str] = { "ConCssChoiceDimension", "ConCssCountDimension", "ConCssNumberDimension", "ConCssSwitchDimension" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ConCrossSectionParametricDefinitionAllOfDimensions.model_construct()
        error_messages = []
        match = 0
        # validate data type: ConCssNumberDimension
        if not isinstance(v, ConCssNumberDimension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConCssNumberDimension`")
        else:
            match += 1
        # validate data type: ConCssCountDimension
        if not isinstance(v, ConCssCountDimension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConCssCountDimension`")
        else:
            match += 1
        # validate data type: ConCssSwitchDimension
        if not isinstance(v, ConCssSwitchDimension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConCssSwitchDimension`")
        else:
            match += 1
        # validate data type: ConCssChoiceDimension
        if not isinstance(v, ConCssChoiceDimension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConCssChoiceDimension`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ConCrossSectionParametricDefinitionAllOfDimensions with oneOf schemas: ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ConCrossSectionParametricDefinitionAllOfDimensions with oneOf schemas: ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("$type")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `$type` in the input.")

        # check if data type is `ConCssChoiceDimension`
        if _data_type == "IdeaStatiCa.Api.Connection.Model.Material.ConCssChoiceDimension, IdeaStatiCa.Api":
            instance.actual_instance = ConCssChoiceDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssCountDimension`
        if _data_type == "IdeaStatiCa.Api.Connection.Model.Material.ConCssCountDimension, IdeaStatiCa.Api":
            instance.actual_instance = ConCssCountDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssNumberDimension`
        if _data_type == "IdeaStatiCa.Api.Connection.Model.Material.ConCssNumberDimension, IdeaStatiCa.Api":
            instance.actual_instance = ConCssNumberDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssSwitchDimension`
        if _data_type == "IdeaStatiCa.Api.Connection.Model.Material.ConCssSwitchDimension, IdeaStatiCa.Api":
            instance.actual_instance = ConCssSwitchDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssChoiceDimension`
        if _data_type == "ConCssChoiceDimension":
            instance.actual_instance = ConCssChoiceDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssCountDimension`
        if _data_type == "ConCssCountDimension":
            instance.actual_instance = ConCssCountDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssNumberDimension`
        if _data_type == "ConCssNumberDimension":
            instance.actual_instance = ConCssNumberDimension.from_json(json_str)
            return instance

        # check if data type is `ConCssSwitchDimension`
        if _data_type == "ConCssSwitchDimension":
            instance.actual_instance = ConCssSwitchDimension.from_json(json_str)
            return instance

        # deserialize data into ConCssNumberDimension
        try:
            instance.actual_instance = ConCssNumberDimension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConCssCountDimension
        try:
            instance.actual_instance = ConCssCountDimension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConCssSwitchDimension
        try:
            instance.actual_instance = ConCssSwitchDimension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConCssChoiceDimension
        try:
            instance.actual_instance = ConCssChoiceDimension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ConCrossSectionParametricDefinitionAllOfDimensions with oneOf schemas: ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ConCrossSectionParametricDefinitionAllOfDimensions with oneOf schemas: ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ConCssChoiceDimension, ConCssCountDimension, ConCssNumberDimension, ConCssSwitchDimension]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


