# coding: utf-8

"""
    Connection Rest API 4.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 4.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ideastatica_connection_api.models.con_cross_section_definition import ConCrossSectionDefinition
from typing import Optional, Set
from typing_extensions import Self

class ConCrossSectionLibraryDefinition(ConCrossSectionDefinition):
    """
    ConCrossSectionLibraryDefinition
    """ # noqa: E501
    definition_type: Optional[StrictStr] = Field(default=None, alias="definitionType")
    mprl_name: Optional[StrictStr] = Field(default=None, alias="mprlName")
    mirror_y: Optional[StrictBool] = Field(default=None, alias="mirrorY")
    mirror_z: Optional[StrictBool] = Field(default=None, alias="mirrorZ")
    type: Optional[StrictStr] = Field(default='IdeaStatiCa.Api.Connection.Model.Material.ConCrossSectionLibraryDefinition, IdeaStatiCa.Api', alias="$type")
    __properties: ClassVar[List[str]] = ["definitionType", "materialName", "mprlName", "mirrorY", "mirrorZ", "$type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConCrossSectionLibraryDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "definition_type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if definition_type (nullable) is None
        # and model_fields_set contains the field
        if self.definition_type is None and "definition_type" in self.model_fields_set:
            _dict['definitionType'] = None

        # set to None if material_name (nullable) is None
        # and model_fields_set contains the field
        if self.material_name is None and "material_name" in self.model_fields_set:
            _dict['materialName'] = None

        # set to None if mprl_name (nullable) is None
        # and model_fields_set contains the field
        if self.mprl_name is None and "mprl_name" in self.model_fields_set:
            _dict['mprlName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConCrossSectionLibraryDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "definitionType": obj.get("definitionType"),
            "materialName": obj.get("materialName"),
            "mprlName": obj.get("mprlName"),
            "mirrorY": obj.get("mirrorY"),
            "mirrorZ": obj.get("mirrorZ"),
            "$type": obj.get("$type") if obj.get("$type") is not None else 'IdeaStatiCa.Api.Connection.Model.Material.ConCrossSectionLibraryDefinition, IdeaStatiCa.Api'
        })
        return _obj


