# coding: utf-8

"""
    Connection Rest API 4.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 4.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConPropertyOwnerKind(str, Enum):
    """
    ConPropertyOwnerKind
    """

    """
    allowed enum values
    """
    OPERATION = 'operation'
    MEMBER = 'member'
    CROSSSECTION = 'crossSection'
    MATERIAL = 'material'
    BOLTASSEMBLY = 'boltAssembly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConPropertyOwnerKind from a JSON string"""
        return cls(json.loads(json_str))


