# coding: utf-8

"""
    Connection Rest API 5.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 5.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConShearForceTransferMethod(str, Enum):
    """
    ConShearForceTransferMethod
    """

    """
    allowed enum values
    """
    FRICTION = 'friction'
    SHEARLUG = 'shearLug'
    ANCHORBENDING = 'anchorBending'
    SLIDING = 'sliding'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConShearForceTransferMethod from a JSON string"""
        return cls(json.loads(json_str))


