# coding: utf-8

"""
    Connection Rest API 5.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 5.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ideastatica_connection_api.models.con_cut_by_target import ConCutByTarget
from ideastatica_connection_api.models.con_cutting_method import ConCuttingMethod
from ideastatica_connection_api.models.con_plate_side import ConPlateSide
from ideastatica_connection_api.models.con_weld_data import ConWeldData
from typing import Optional, Set
from typing_extensions import Self

class ConPlateCutOperation(BaseModel):
    """
    ConPlateCutOperation
    """ # noqa: E501
    modified_object: Optional[ConCutByTarget] = Field(default=None, alias="modifiedObject")
    cut_by: Optional[ConCutByTarget] = Field(default=None, alias="cutBy")
    cutting_method: Optional[ConCuttingMethod] = Field(default=None, alias="cuttingMethod")
    remaining_part: Optional[ConPlateSide] = Field(default=None, alias="remainingPart")
    offset: Optional[Union[StrictFloat, StrictInt]] = None
    weld: Optional[ConWeldData] = None
    is_imported: Optional[StrictBool] = Field(default=None, alias="isImported")
    operation_type: Optional[StrictStr] = Field(default=None, alias="operationType")
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    active: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["modifiedObject", "cutBy", "cuttingMethod", "remainingPart", "offset", "weld", "isImported", "operationType", "id", "name", "active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConPlateCutOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of modified_object
        if self.modified_object:
            _dict['modifiedObject'] = self.modified_object.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cut_by
        if self.cut_by:
            _dict['cutBy'] = self.cut_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of weld
        if self.weld:
            _dict['weld'] = self.weld.to_dict()
        # set to None if operation_type (nullable) is None
        # and model_fields_set contains the field
        if self.operation_type is None and "operation_type" in self.model_fields_set:
            _dict['operationType'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConPlateCutOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "modifiedObject": ConCutByTarget.from_dict(obj["modifiedObject"]) if obj.get("modifiedObject") is not None else None,
            "cutBy": ConCutByTarget.from_dict(obj["cutBy"]) if obj.get("cutBy") is not None else None,
            "cuttingMethod": obj.get("cuttingMethod"),
            "remainingPart": obj.get("remainingPart"),
            "offset": obj.get("offset"),
            "weld": ConWeldData.from_dict(obj["weld"]) if obj.get("weld") is not None else None,
            "isImported": obj.get("isImported"),
            "operationType": obj.get("operationType"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "active": obj.get("active")
        })
        return _obj


