# coding: utf-8

"""
    Connection Rest API 3.0

    IDEA StatiCa Connection API, used for the automated design and calculation of steel connections.

    The version of the OpenAPI document: 3.0
    Contact: info@ideastatica.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ConStiffnessAnalysis(BaseModel):
    """
    ConStiffnessAnalysis
    """ # noqa: E501
    theoretical_length_z: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="theoreticalLengthZ")
    theoretical_length_y: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="theoreticalLengthY")
    __properties: ClassVar[List[str]] = ["theoreticalLengthZ", "theoreticalLengthY"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConStiffnessAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if theoretical_length_z (nullable) is None
        # and model_fields_set contains the field
        if self.theoretical_length_z is None and "theoretical_length_z" in self.model_fields_set:
            _dict['theoreticalLengthZ'] = None

        # set to None if theoretical_length_y (nullable) is None
        # and model_fields_set contains the field
        if self.theoretical_length_y is None and "theoretical_length_y" in self.model_fields_set:
            _dict['theoreticalLengthY'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConStiffnessAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "theoreticalLengthZ": obj.get("theoreticalLengthZ"),
            "theoreticalLengthY": obj.get("theoreticalLengthY")
        })
        return _obj


