/*
 * RCS Rest API 1.0
 *
 * IDEA StatiCa RCS API, used for the automated design and calculation of reinforced concrete sections.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@ideastatica.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using IdeaRS.OpenModel;
using IdeaStatiCa.Api.RCS.Model;
using IdeaStatiCa.RcsApi.Client;
using IdeaStatiCa.RcsApi.Model;

namespace IdeaStatiCa.RcsApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaterialApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        object AddConcreteMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0);

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        ApiResponse<object> AddConcreteMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        object AddPrestressMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0);

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        ApiResponse<object> AddPrestressMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        object AddReinforcementMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0);

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        ApiResponse<object> AddReinforcementMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        List<object> GetAllMaterials(Guid projectId, int operationIndex = 0);

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        ApiResponse<List<object>> GetAllMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        List<object> GetConcreteMaterials(Guid projectId, int operationIndex = 0);

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        ApiResponse<List<object>> GetConcreteMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        List<object> GetPrestressMaterials(Guid projectId, int operationIndex = 0);

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        ApiResponse<List<object>> GetPrestressMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0);
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        List<object> GetReinforcementMaterials(Guid projectId, int operationIndex = 0);

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>        
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        ApiResponse<List<object>> GetReinforcementMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaterialApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        System.Threading.Tasks.Task<object> AddConcreteMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> AddConcreteMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        System.Threading.Tasks.Task<object> AddPrestressMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> AddPrestressMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        System.Threading.Tasks.Task<object> AddReinforcementMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> AddReinforcementMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        System.Threading.Tasks.Task<List<object>> GetAllMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<object>>> GetAllMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        System.Threading.Tasks.Task<List<object>> GetConcreteMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<object>>> GetConcreteMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        System.Threading.Tasks.Task<List<object>> GetPrestressMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<object>>> GetPrestressMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        System.Threading.Tasks.Task<List<object>> GetReinforcementMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<object>>> GetReinforcementMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaterialApi : IMaterialApiSync, IMaterialApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MaterialApi : IMaterialApi
    {
        private IdeaStatiCa.RcsApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MaterialApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MaterialApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaterialApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MaterialApi(string basePath)
        {
            this.Configuration = IdeaStatiCa.RcsApi.Client.Configuration.MergeConfigurations(
                IdeaStatiCa.RcsApi.Client.GlobalConfiguration.Instance,
                new IdeaStatiCa.RcsApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new IdeaStatiCa.RcsApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new IdeaStatiCa.RcsApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = IdeaStatiCa.RcsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaterialApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MaterialApi(IdeaStatiCa.RcsApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = IdeaStatiCa.RcsApi.Client.Configuration.MergeConfigurations(
                IdeaStatiCa.RcsApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new IdeaStatiCa.RcsApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new IdeaStatiCa.RcsApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = IdeaStatiCa.RcsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaterialApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MaterialApi(IdeaStatiCa.RcsApi.Client.ISynchronousClient client, IdeaStatiCa.RcsApi.Client.IAsynchronousClient asyncClient, IdeaStatiCa.RcsApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = IdeaStatiCa.RcsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IdeaStatiCa.RcsApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public IdeaStatiCa.RcsApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IdeaStatiCa.RcsApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IdeaStatiCa.RcsApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        public object AddConcreteMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = AddConcreteMaterialWithHttpInfo(projectId, rcsMprlElement);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<object> AddConcreteMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddConcreteMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<object>("/api/1/projects/{projectId}/materials/concrete", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddConcreteMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        public async System.Threading.Tasks.Task<object> AddConcreteMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = await AddConcreteMaterialWithHttpInfoAsync(projectId, rcsMprlElement, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<object>> AddConcreteMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddConcreteMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<object>("/api/1/projects/{projectId}/materials/concrete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddConcreteMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        public object AddPrestressMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = AddPrestressMaterialWithHttpInfo(projectId, rcsMprlElement);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<object> AddPrestressMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddPrestressMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<object>("/api/1/projects/{projectId}/materials/prestress", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddPrestressMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        public async System.Threading.Tasks.Task<object> AddPrestressMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = await AddPrestressMaterialWithHttpInfoAsync(projectId, rcsMprlElement, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<object>> AddPrestressMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddPrestressMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<object>("/api/1/projects/{projectId}/materials/prestress", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddPrestressMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>object</returns>
        public object AddReinforcementMaterial(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = AddReinforcementMaterialWithHttpInfo(projectId, rcsMprlElement);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
/// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of object</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<object> AddReinforcementMaterialWithHttpInfo(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddReinforcementMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<object>("/api/1/projects/{projectId}/materials/reinforcement", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddReinforcementMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of object</returns>
        public async System.Threading.Tasks.Task<object> AddReinforcementMaterialAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<object> localVarResponse = await AddReinforcementMaterialWithHttpInfoAsync(projectId, rcsMprlElement, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new material to the project. The material type is determined by the endpoint path. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="rcsMprlElement">Material data to add (MPRL name) (optional)</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (object)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<object>> AddReinforcementMaterialWithHttpInfoAsync(Guid projectId, RcsMprlElement rcsMprlElement = default(RcsMprlElement), string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.Data = rcsMprlElement;

            localVarRequestOptions.Operation = "MaterialApi.AddReinforcementMaterial";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<object>("/api/1/projects/{projectId}/materials/reinforcement", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddReinforcementMaterial", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        public List<object> GetAllMaterials(Guid projectId, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = GetAllMaterialsWithHttpInfo(projectId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> GetAllMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetAllMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<object>>("/api/1/projects/{projectId}/materials", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        public async System.Threading.Tasks.Task<List<object>> GetAllMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = await GetAllMaterialsWithHttpInfoAsync(projectId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>>> GetAllMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetAllMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<object>>("/api/1/projects/{projectId}/materials", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        public List<object> GetConcreteMaterials(Guid projectId, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = GetConcreteMaterialsWithHttpInfo(projectId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> GetConcreteMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetConcreteMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<object>>("/api/1/projects/{projectId}/materials/concrete", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConcreteMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        public async System.Threading.Tasks.Task<List<object>> GetConcreteMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = await GetConcreteMaterialsWithHttpInfoAsync(projectId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>>> GetConcreteMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetConcreteMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<object>>("/api/1/projects/{projectId}/materials/concrete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConcreteMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        public List<object> GetPrestressMaterials(Guid projectId, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = GetPrestressMaterialsWithHttpInfo(projectId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> GetPrestressMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetPrestressMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<object>>("/api/1/projects/{projectId}/materials/prestress", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPrestressMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        public async System.Threading.Tasks.Task<List<object>> GetPrestressMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = await GetPrestressMaterialsWithHttpInfoAsync(projectId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>>> GetPrestressMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetPrestressMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<object>>("/api/1/projects/{projectId}/materials/prestress", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPrestressMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;object&gt;</returns>
        public List<object> GetReinforcementMaterials(Guid projectId, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = GetReinforcementMaterialsWithHttpInfo(projectId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;object&gt;</returns>
        public IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> GetReinforcementMaterialsWithHttpInfo(Guid projectId, string requestedType = null, int operationIndex = 0)
        {
            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;

            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept != null)
                {
                    localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetReinforcementMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<object>>("/api/1/projects/{projectId}/materials/reinforcement", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReinforcementMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;object&gt;</returns>
        public async System.Threading.Tasks.Task<List<object>> GetReinforcementMaterialsAsync(Guid projectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>> localVarResponse = await GetReinforcementMaterialsWithHttpInfoAsync(projectId, null, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get materials from the project. Use specific path to filter by material type. 
        /// </summary>
        /// <exception cref="IdeaStatiCa.RcsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="requestedType">Requested content type in the response.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;object&gt;)</returns>
        public async System.Threading.Tasks.Task<IdeaStatiCa.RcsApi.Client.ApiResponse<List<object>>> GetReinforcementMaterialsWithHttpInfoAsync(Guid projectId, string requestedType = null, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            IdeaStatiCa.RcsApi.Client.RequestOptions localVarRequestOptions = new IdeaStatiCa.RcsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            string localVarAccept = requestedType;
            if(string.IsNullOrEmpty(localVarAccept))
            {
                localVarAccept = IdeaStatiCa.RcsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            }

            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("projectId", IdeaStatiCa.RcsApi.Client.ClientUtils.ParameterToString(projectId)); // path parameter

            localVarRequestOptions.Operation = "MaterialApi.GetReinforcementMaterials";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<object>>("/api/1/projects/{projectId}/materials/reinforcement", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReinforcementMaterials", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
