//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaRS.OpenModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdeaRS.OpenModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad weld material property.
        /// </summary>
        internal static string ErrBadWeldMaterialProperty {
            get {
                return ResourceManager.GetString("ErrBadWeldMaterialProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolts are too close to each other..
        /// </summary>
        internal static string ErrBoltsTooClose {
            get {
                return ResourceManager.GetString("ErrBoltsTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolts are too close to plate edge or outside of the connected plate..
        /// </summary>
        internal static string ErrBoltsTooCloseEdge {
            get {
                return ResourceManager.GetString("ErrBoltsTooCloseEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of plates in contact is out of limit (sin(alfa) &gt; 0.001)..
        /// </summary>
        internal static string ErrContactsAngle {
            get {
                return ResourceManager.GetString("ErrContactsAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curve mustn&apos;t be a decrease function..
        /// </summary>
        internal static string ErrCurveDecreaseFunction {
            get {
                return ResourceManager.GetString("ErrCurveDecreaseFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curve derivation is out of range..
        /// </summary>
        internal static string ErrCurveDerivation {
            get {
                return ResourceManager.GetString("ErrCurveDerivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curve isn&apos;t a function..
        /// </summary>
        internal static string ErrCurveFunction {
            get {
                return ResourceManager.GetString("ErrCurveFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curve isn&apos;t set..
        /// </summary>
        internal static string ErrCurveNotSet {
            get {
                return ResourceManager.GetString("ErrCurveNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The curve doesn&apos;t contain the point (0, 0)..
        /// </summary>
        internal static string ErrCurveZeroPoint {
            get {
                return ResourceManager.GetString("ErrCurveZeroPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data object in Data Model was not created. Internal error..
        /// </summary>
        internal static string ErrDataObjectNotCreated {
            get {
                return ResourceManager.GetString("ErrDataObjectNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material properties don&apos;t satisfy the condition: &quot;(1.0 - E / (2.0 * (1.0 + Poisson) * G)) &lt; 0.01&quot;..
        /// </summary>
        internal static string ErrIncorrectMaterialEGP {
            get {
                return ResourceManager.GetString("ErrIncorrectMaterialEGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect material E-modulus..
        /// </summary>
        internal static string ErrIncorrentMaterialE {
            get {
                return ResourceManager.GetString("ErrIncorrentMaterialE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cross-section parameter in the Open Model Cross-section .
        /// </summary>
        internal static string ErrNoCrossSectionParameter {
            get {
                return ResourceManager.GetString("ErrNoCrossSectionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No equivalent Data object in the Data Model..
        /// </summary>
        internal static string ErrNoEquivalentObjectInDataModel {
            get {
                return ResourceManager.GetString("ErrNoEquivalentObjectInDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Open Model object in the Idea Open Model..
        /// </summary>
        internal static string ErrNoObjectInOpenModel {
            get {
                return ResourceManager.GetString("ErrNoObjectInOpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Open Model object..
        /// </summary>
        internal static string ErrNoOpenObject {
            get {
                return ResourceManager.GetString("ErrNoOpenObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No referenced Open Model object in the Idea Open Model..
        /// </summary>
        internal static string ErrNoReferenceObjectInOpenModel {
            get {
                return ResourceManager.GetString("ErrNoReferenceObjectInOpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt grade is not allowed in slip-resistant joints..
        /// </summary>
        internal static string ErrPreloadedBoltGrade {
            get {
                return ResourceManager.GetString("ErrPreloadedBoltGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry of the polyline is not valid. The segments are not continuous or they have a different orientation..
        /// </summary>
        internal static string ErrValidPolyline {
            get {
                return ResourceManager.GetString("ErrValidPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of the range..
        /// </summary>
        internal static string ErrValueOutOfRange {
            get {
                return ResourceManager.GetString("ErrValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected member is overloaded.
        /// </summary>
        internal static string ErrWarningLoad {
            get {
                return ResourceManager.GetString("ErrWarningLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General warning.
        /// </summary>
        internal static string GeneralWarning {
            get {
                return ResourceManager.GetString("GeneralWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material in not in library..
        /// </summary>
        internal static string NoInLibraryError {
            get {
                return ResourceManager.GetString("NoInLibraryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation timeout.
        /// </summary>
        internal static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of points of the curve is exceed 100..
        /// </summary>
        internal static string WarnCurveCount {
            get {
                return ResourceManager.GetString("WarnCurveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No equivalent property in the Data object.
        /// </summary>
        internal static string WarnNoPropertyInData {
            get {
                return ResourceManager.GetString("WarnNoPropertyInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of bars in the reinforced cross-section are in collision..
        /// </summary>
        internal static string WarnReinforcementBarsCollision {
            get {
                return ResourceManager.GetString("WarnReinforcementBarsCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of the range..
        /// </summary>
        internal static string WarnValueOutOfRange {
            get {
                return ResourceManager.GetString("WarnValueOutOfRange", resourceCulture);
            }
        }
    }
}
