name: .NET build verification

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  BuildAndTest:
    name: "Build, Test and create Nuget"
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Dotnet restore dependencies
      run: dotnet restore ./src/IdeaStatiCa.Public.sln
      working-directory: main

    - name: Build
      run: msbuild ./src/IdeaStatiCa.Public.sln /p:Configuration=Release
      working-directory: main

    - name: Test
      run: 'vstest.console.exe .\src\IdeaStatiCa.Plugin.Tests\bin\Release\IdeaStatiCa.Plugin.Tests.dll'
      working-directory: main
      
    - name: Pack nugets
      run: ./buildNugets.ps1
      working-directory: main

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Idea nugets
        path: |
          ${{ github.workspace }}\**\*Idea*.nupkg
