name: .NET build verification

on:
  pull_request:
    branches: [ main, release_* ]

jobs:
  IdeaStatiCa_Public:
    name: "Build and Test IdeaStatiCa.Public.sln"
    runs-on: windows-latest

    env: # Define the global configuration variable
      TreatWarningsAsErrors: "false" # Set to "true" or "false" as needed
      DOTNET_VERSION: '9.0.301'
      NUGET_BINARY: '6.13.2'

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        path: main

    - name: 'Setup msbuild'
      uses: microsoft/setup-msbuild@v1

    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $env:DOTNET_VERSION

    - name: 'Setup nuget.exe'
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: $env:NUGET_BINARY

    - name: 'NuGet restore dependencies'
      run: nuget restore ./src/IdeaStatiCa.Public.sln
      working-directory: main

    - name: 'Build'
      run:  msbuild ./src/IdeaStatiCa.Public.sln /p:Configuration=Release /p:TreatWarningsAsErrors=$env:TreatWarningsAsErrors
      working-directory: main

    - name: 'Test'
      run: dotnet test --configuration "Release" --blame --collect "Code Coverage" ./src/IdeaStatiCa.Public.sln /p:TreatWarningsAsErrors=$env:TreatWarningsAsErrors
      working-directory: main

  IdeaStatiCa-SDK-Examples:
    name: "Build IdeaStatiCa-SDK-Examples.sln"
    runs-on: windows-latest

    env: # Define the global configuration variable
      TreatWarningsAsErrors: "false" # Set to "true" or "false" as needed

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        path: main

    - name: 'Setup msbuild'
      uses: microsoft/setup-msbuild@v1

    - name: 'Setup nuget.exe'
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: $env:NUGET_BINARY

    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $env:DOTNET_VERSION

    - name: 'NuGet restore dependencies'
      run: nuget restore ./examples/IdeaStatiCa-SDK-Examples.sln 
      working-directory: main

    - name: 'Dotnet restore dependencies'
      run: dotnet restore ./examples/IdeaStatiCa-SDK-Examples.sln
      working-directory: main

    - name: 'Build'
      run:  msbuild ./examples/IdeaStatiCa-SDK-Examples.sln /p:Configuration=Release /p:TreatWarningsAsErrors=$env:TreatWarningsAsErrors
      working-directory: main

  ConRestApiClient:
    name: "Build ConRestApiClient.sln"
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        path: main

    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $env:DOTNET_VERSION

    - name: 'Dotnet restore dependencies'
      run: dotnet restore ./src/api-sdks/connection-api/clients/csharp/ConRestApiClient.sln
      working-directory: main

    - name: 'Build'
      run:  dotnet build ./src/api-sdks/connection-api/clients/csharp/ConRestApiClient.sln /p:Configuration=Release
      working-directory: main

  RcsRestApiClient:
    name: "Build RcsRestApiClient.sln"
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        path: main

    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $env:DOTNET_VERSION

    - name: 'Dotnet restore dependencies'
      run: dotnet restore ./src/api-sdks/rcs-api/clients/csharp/RcsRestApiClient.sln
      working-directory: main

    - name: 'Build'
      run:  dotnet build ./src/api-sdks/rcs-api/clients/csharp/RcsRestApiClient.sln /p:Configuration=Release
      working-directory: main      
