name: .NET build verification

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  BuildAndTest:
    name: "Build and Test IOM"
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1

    - name: Setup nuget.exe
      uses: NuGet/setup-nuget@v1
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2

    - name: Nuget restore dependencies
      run: nuget restore ./src/IdeaStatiCa.Public.sln
      working-directory: main

    - name: Dotnet restore dependencies
      run: dotnet restore ./src/IdeaStatiCa.Public.sln
      working-directory: main

    - name: Build
      run: msbuild ./src/IdeaStatiCa.Public.sln /p:Configuration=Release
      working-directory: main

    - name: Test
      run: 'dotnet test --configuration "Release" --blame --collect "Code Coverage" ./src/IdeaStatiCa.Public.sln'
      working-directory: main